---
- hosts: master
  become: yes
  become_method: sudo

  tasks:
  - name: initialize the cluster
    shell:  kubeadm init --pod-network-cidr={{ pod_network_cidr }} >> cluster_initialized.txt
    args:
      chdir: $HOME
      creates: cluster_initialized.txt

  - name: create .kube directory
    become: yes
    become_user: "{{ k8s_admin }}"
    file:
      path: $HOME/.kube
      state: directory
      mode: 0755

  - name: copy admin.conf to user's kube config
    copy:
      src: /etc/kubernetes/admin.conf
      dest: /home/{{ k8s_admin }}/.kube/config
      remote_src: yes
      owner: "{{ k8s_admin }}"

  - name: install Pod network
    become: yes
    become_user: "{{ k8s_admin }}"
    shell: kubectl apply -f flannel.yml
    args:
      chdir: $HOME
      creates: pod_network_setup.txt
